#!/usr/bin/python
#
# COPYRIGHT: Copyright (c) 2014 Yong Yang.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  (http://www.gnu.org/copyleft/gpl.html)
#
# 3-Jul-2015	Yong Yang	Created this.

"""
A tool that could show tasks information on Linux per-CPU runq
"""

import sys
from optparse import OptionParser
import re
import subprocess
import time
from time import sleep

__version__ = '0.1'

def gen_numa():
    """Generate NUMA info"""
    cpunodes = {}
    numacores = {}
    out = subprocess.Popen('numactl --hardware | grep cpus', shell=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    errtxt = out.stderr.readline()
    if errtxt:
        print errtxt + '\r\n'
        print "Is numactl installed?\r"
        exit(1)
    for line in out.stdout.readlines():
        arr = line.split()
        if arr[0] == "node" and arr[2] == "cpus:" and len(arr) > 3:
            node = arr[1]
            numacores[node] = arr[3:]
            for core in arr[3:]:
                cpunodes[core] = node
    return numacores, cpunodes

def print_stat(numacores, nr_running, nr_switches):
    """print runqstat header"""

    width = 16
    width = min(width, len(nr_switches[0]))
    node = 0
    header = '           '
    while node < len(numacores):
        header += (' %' + str(width) + 's ') % ("Node" + str(node))
        data1 = ''
        data2 = ''
        node_sum1 = 0
        node_sum2 = 0
        for cpu in numacores[str(node)]:
            header += (' %' + str(width) + 's ') % ("CPU" + cpu)
            data1 += (' %' + str(width) + 's ') % nr_running[int(cpu)]
            data2 += (' %' + str(width) + 's ') % nr_switches[int(cpu)]
            node_sum1 += int(nr_running[int(cpu)])
            node_sum2 += int(nr_switches[int(cpu)])
        print header
        print ('nr_running %' + str(width) + 's ') % str(node_sum1) + data1
        print ('nr_switches %' + str(width) + 's ') % str(node_sum2) + data2
        node += 1
    print '\n'


def header_parse(out):
    """sched_debug header parse"""

    while True:
        line = out.readline()
        if re.search("Sched Debug Version:", line):
            print line
        if re.search("sched_clock_stable", line):
            print line
            break

def sysctl_sched_parse(out):
    """sysctl_sched parse"""

    print_start = 0
    while True:
        line = out.readline()
        if re.search("sysctl_sched", line):
            print_start = 1
        if print_start:
            print line
        if print_start and re.search("^\n$", line):
            print_start = 0
            break

def runq_parse(out, numacores):
    """runq parse"""

    nr_running = {}
    nr_switches = {}
    cpu = 0
    cpu_found = 0
    nr_running[cpu] = -1
    nr_switches[cpu] = -1
    for line in out.readlines():
        if re.search("cpu#", line):
            cpu_found = 1
        if re.search("\.nr_running", line):
            if cpu_found:
                cpu_data = line.split(':')
                nr_running[cpu] = cpu_data[1].strip('\n')
        if re.search("\.nr_switches", line):
                cpu_data = line.split(':')
                nr_switches[cpu] = cpu_data[1].strip('\n')
                cpu += 1
                cpu_found = 0

    print_stat(numacores, nr_running, nr_switches)

def runq_stat(seconds):
    """Main I/O loop"""

    numacores, cpunodes = gen_numa()

    print_once = 1

    try:
        out = open('/proc/sched_debug', 'r')

        while True:
            if print_once == 1:
                header_parse(out)
                sysctl_sched_parse(out)
                print "CPU runq task numbers for every %d second(s)\n" % seconds
                print_once = 0

            print time.ctime() + '\n'
            runq_parse(out, numacores)

            for _ in range(0, seconds * 10):
                sleep(.1)

            out.seek(0,0)

    except IOError:
        print "Error: can't open /proc/sched_debug"
        print "please make sure kernel is configed with SCHED_DEBUG."
        return

    out.close()

def main(args):
    """Parse arguments, call main loop"""

    parser = OptionParser(description=__doc__)

    parser.add_option("-v", "--version", action="store_true",
                      help="get version")
    parser.add_option("-t", "--time", default='5',
                      help="update interval in seconds")

    options = parser.parse_args(args)[0]

    if options.version:
        print __version__
        return 0

    try:
        runq_stat(int(options.time))
    except (KeyboardInterrupt, SystemExit):
        pass

if __name__ == "__main__":
    sys.exit(main(sys.argv))
